apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-1-cluster2
spec:
  selector:
    matchLabels:
      app: redis-1-cluster2
  template:
    metadata:
      labels:
        app: redis-1-cluster2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: redis
                operator: In
                values:
                - cluster2.node1.<CLUSTER_ID>
      hostNetwork: true
      containers:
      - name: redis
        env:
        - name: REDIS_PASSWORD
          value: bitnami
        - name: REDIS_NODES
          value: <NODESIP>
        image: docker.io/bitnami/redis-cluster:7.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: cluster2node1<CLUSTER_ID>
          mountPath: /bitnami/redis/data
      volumes:
      - name: cluster2node1<CLUSTER_ID>
        hostPath:
          path: /tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-2-cluster2
spec:
  selector:
    matchLabels:
      app: redis-2-cluster2
  template:
    metadata:
      labels:
        app: redis-2-cluster2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: redis
                operator: In
                values:
                - cluster2.node2.<CLUSTER_ID>
      hostNetwork: true
      containers:
      - name: redis
        env:
        - name: REDIS_PASSWORD
          value: bitnami
        - name: REDIS_NODES
          value: <NODESIP>
        image: docker.io/bitnami/redis-cluster:7.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: cluster2node2<CLUSTER_ID>
          mountPath: /bitnami/redis/data
      volumes:
      - name: cluster2node2<CLUSTER_ID>
        hostPath:
          path: /tmp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-3-cluster2
spec:
  selector:
    matchLabels:
      app: redis-3-cluster2
  template:
    metadata:
      labels:
        app: redis-3-cluster2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: redis
                operator: In
                values:
                - cluster2.node3.<CLUSTER_ID>
      hostNetwork: true
      containers:
      - name: redis
        env:
        - name: REDIS_PASSWORD
          value: bitnami
        - name: REDIS_NODES
          value: <NODESIP>
        image: docker.io/bitnami/redis-cluster:7.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: cluster2node3<CLUSTER_ID>
          mountPath: /bitnami/redis/data
      volumes:
      - name: cluster2node3<CLUSTER_ID>
        hostPath:
          path: /tmp