apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  CLUSTER1_NAME: {{ .Values.cluster1.name | b64enc }}  # Base64 encoded value for "redis-1"
  CLUSTER_ID: {{ .Values.cluster.id | b64enc }}  # Base64 encoded value for "abcd"
  CLUSTER2_NAME: {{ .Values.cluster2.name | b64enc }}   # Base64 encoded value for "redis-2"
  CLUSTER_PASS: {{ .Values.cluster.password | b64enc }}   # Base64 encoded value for "bitnami"
  CF_API_KEY: {{ .Values.cloudflare.api_key | b64enc }}  # Base64 encoded CF_API_KEY
  CF_ZONE_ID: {{ .Values.cloudflare.zone_id | b64enc }}    # Base64 encoded CF_ZONE_ID
  AWS_ACCESS_KEY_ID: {{ .Values.aws.AWS_ACCESS_KEY_ID | b64enc }}             # Base64 encoded AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.AWS_SECRET_ACCESS_KEY | b64enc }} # Base64 encoded AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: {{ .Values.aws.AWS_DEFAULT_REGION | b64enc }}  # Base64 encoded value for "us-east-1"

